eureka.server.ip.peer1: 127.0.0.1
eureka.server.ip.peer2: 127.0.0.1
eureka.server.ip.peer3: 127.0.0.1
eureka.server.ip.peer4: 127.0.0.1
peer1.port: 8762
peer2.port: 8763
peer3.port: 8764
peer4.port: 8765