spring:
  application:
    name: eureka-provider
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://horcrux:hor66@172.17.0.27:8765/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}

providerkey: providerFromConfig
