server:
  port: 9999
spring:
  cloud:
    config:
      server:
        svn:
          uri: https://172.16.0.25/svn/kim_project/trunk/babel_horcrux/horcrux-config
          username: lang.li
          password: password123
        default-label: devrepo
#        default-label: highavalirepo
#        default-label: trunk
  profiles:
    active: subversion
  application:
    name: config-server
  jmx:
    default-domain: config-server


logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.cloud.config.server: DEBUG

#kafka
spring.cloud.stream.kafka.binder.zk-nodes: 172.16.0.27:2181
spring.cloud.stream.kafka.binder.brokers: 172.16.0.27:9092